{% set name = "pyhacrf-datamade" %}
{% set version = "0.2.7" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyhacrf-datamade-{{ version }}.tar.gz
  sha256: 6e898ab725af37337773fc2076d617255f64db018f2dd486b9e4f8ecda15cfed

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - cython
    - numpy
    - pip
    - python
    - setuptools
    - wheel
  run:
    - pylbfgs
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - pyhacrf
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/dedupeio/pyhacrf
  summary: Hidden alignment conditional random field for classifying string pairs.
  description: |
    Hidden alignment conditional random field for classifying string
    pairs - a learnable edit distance.
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  doc_url: https://github.com/dedupeio/pyhacrf
  dev_url: https://github.com/dedupeio/pyhacrf

extra:
  recipe-maintainers:
    - osamples
    - izahn
